require 'ra-res.plugins'
require 'ra-res.bufferline'
-- require 'ra-res.coc'
require 'ra-res.treesitter'
require 'ra-res.telescope'
require 'ra-res.project'
require 'ra-res.mappings'
require 'ra-res.lualine'
require 'ra-res.nvim-tree'
require 'ra-res.colorizer'
require 'ra-res.devicons'
require 'ra-res.toggleterm'
require 'ra-res.cmp'
require 'ra-res.lsp'
require 'ra-res.gitsigns'
require 'ra-res.jabs'
require 'ra-res.neoscroll'
