require 'ra-res.plugins'
require 'ra-res.coc'
require 'ra-res.treesitter'
require 'ra-res.telescope'
require 'ra-res.rooter'
require 'ra-res.mappings'
require 'ra-res.lualine'
require 'ra-res.nerdtree'
