require 'ra-res.plugins'
require 'ra-res.coc'
require 'ra-res.treesitter'
require 'ra-res.telescope'
-- require 'ra-res.rooter' -- Replaced with project.nvim
require 'ra-res.project'
require 'ra-res.mappings'
require 'ra-res.lualine'
require 'ra-res.nerdtree'
require 'ra-res.colorizer'
